server:
  port: 80
spring:
  application:
    name: crowd-zuul
  redis:
    host: 192.168.181.128
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
zuul:
  routes:
    crowd-portal:
      service-id: crowd-auth
      path: /**
    crowd-project:
      service-id: crowd-project
      path: /project/**
    crowd-order:
      service-id: crowd-order
      path: /order/**
  ignored-services: "*"
  sensitive-headers: "*"

