server:
  port: 5000
Spring:
  application:
    name: crowd-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.181.128
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
aliyun:
  oss:
    access-key-id: LTAI4GHoLhKodm737HCHGHat
    access-key-secret: mBebL4e1ggt9FjvQFqQx8wZYfrzMpW
    bucket-domain: http://test210313.oss-cn-beijing.aliyuncs.com
    bucket-name: test210313
    end-point: http://oss-cn-beijing.aliyuncs.com